project:
  type: website
  output-dir: _book
  render:
    - index.qmd
    - about.qmd
    - measuring-same-day-readmits.qmd
    - understanding-medicare-aco-assignment.qmd
    - customizing-the-tuva-data-model.qmd
    - building-a-claims-data-platform.qmd
    - intro-dbt-for-healthcare.qmd
    - the-problem-with-healthcare-data.qmd

website:
  title: The Tuva Project Blog
  site-url: https://www.thetuvaproject.com/blog

bibliography: references.bib

format:
  html:
    theme: cosmo
    page-navigation: false
    code-fold: true
    css:
      - home.css
      - article.css
    include-before-body: global-header.html
