project:
  type: book
  output-dir: _book

book:
  title: "Claims Data Analytics"
  reader-mode: true
  repo-url: https://github.com/tuva-health/tuva_blog/
  repo-branch: main
  repo-subdir: claims-data-analytics
  repo-actions: [edit, issue]
  page-footer:
    left: |
      Claims Data Analytics · The Tuva Project
    right: |
      Built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://www.thetuvaproject.com/knowledge-base/claims-data-analytics-book/
  search: true
  sidebar:
    style: floating
    collapse-level: 2
  chapters:
    - index.qmd
    - part: parts/healthcare-data-sources.qmd
      chapters:
        - data-sources/claims-data/intro-to-claims.qmd
        - data-sources/member-and-enrollment-data.qmd
        - data-sources/claims-data/header-line.qmd
        - data-sources/claims-data/key-data-elements.qmd
        - data-sources/claims-data/adjustments-denials-reversals.qmd
        - data-sources/claims-data/incurred-paid-runout.qmd
        - data-sources/provider-data.qmd
        - code-sets.qmd
    - part: parts/claims-groupers-and-algorithms.qmd
      chapters:
        - analytics/member-months.qmd
        - claims-groupers-and-algos/attribution.qmd
        - claims-groupers-and-algos/service-categories.qmd
        - claims-groupers-and-algos/encounters.qmd
    - part: parts/analytics.qmd
      chapters:
        - analytics/basic-pmpm.qmd
        - analytics/ed-visits.qmd
        - analytics/hospital-readmissions.qmd
        - analytics/quality-measures.qmd
        - analytics/risk-adjustment.qmd

bibliography: ../references.bib

format:
  html:
    theme:
      - cosmo
      - book.scss
    toc: true
    toc-depth: 3
    code-fold: false
    code-copy: true
    code-link: true
    callout-appearance: simple
